platform:
    - x86
    - x64

build_script:
    - cmd: if "%PLATFORM%" == "x86" call "C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\vcvarsall.bat" %PLATFORM%
    - cmd: if "%PLATFORM%" == "x86" cl.exe -c lib\Remotery.c
    - cmd: call "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat" %PLATFORM%
    - cmd: cl.exe -c lib\Remotery.c