platform:
    - x86
    - x64

build_script:
    # VS2010 doesn't have a 64-bit install

    # VS2010
    - cmd: if "%PLATFORM%" == "x86" call "C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\vcvarsall.bat" %PLATFORM%
    - cmd: if "%PLATFORM%" == "x86" cl.exe -c lib\Remotery.c

    # VS2010 C++ mode
    - cmd: if "%PLATFORM%" == "x86" cl.exe -c -TP lib\Remotery.c

    # VS2015
    - cmd: call "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat" %PLATFORM%
    - cmd: cl.exe -c lib\Remotery.c

    # VS2015 C++ mode
    - cmd: call "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat" %PLATFORM%
    - cmd: cl.exe -c -TP lib\Remotery.c    